---
title: "Client Report - Palmer Penguins"
subtitle: "I explored the Palmer Penguins dataset by creating tables and visualizations from the Python for Data Science (PY4DS) textbook. The project demonstrates how to build reproducible reports, cleanly display tabular data, and use visual encodings (color, shape, smoothing lines) to highlight relationships—in this case, showing that penguins with longer flippers generally weigh more."
author: "[Maia Faith Chambers]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html()
```


```{python}
from palmerpenguins import load_penguins
df = load_penguins()

ggplot(df, aes(x="species")) + geom_bar()
df.head(10)
```

## Include the tables created from PY4DS: CH2 Data Visualization used to create the above chart

__ [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html)


```{python}
# Include and execute your code here
penguins = load_penguins()
penguins.head()

```

The tabular data allows us to easily view each variable in a tidy and simple  manner. These variables are: species, flipper_length_mm, and body_mass_g. 

```{python}

```


## Recreate the example charts from PY4DS: CH2 Data Visualization of the textbook.

I'd like to answer for pracite: 
## Do penguins with longer flippers weigh more or less than penguins with shorter flippers? 
__Recreate the example charts from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) of the textbook. (Hint: copy the chart code from 2.2.3. Creating a Plot, one for each cell below)__


```{python}
ggplot(penguins, aes(x="species")) + geom_bar()

ggplot(data = penguins)

```

```{python}
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point()
)
```
This first plot is very simple, it can be difficult to differentiate though because there is no key indicator on what dots represent what species. 


```{python}
(
    ggplot(
        data=penguins,
        mapping=aes(x="flipper_length_mm", y="body_mass_g", color="species"),
    )
    + geom_point()
)

```


This one is a lot better and shows the different penguins in codination with color. The red dots are the Adelie, the blue is Gentoo, and the green are the Chinstrap penguins. This allows us to see the body mass in comparrison to flipper length based on species. Looking at the graph, it's evident that the Gentoo species has a higher body mass and flipper length.
```{python}
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(mapping=aes(color="species"))
    + geom_smooth(method="lm")
)
```

This graph has a lot better qualities but the one that is best is the next one.

```{python}
(
    ggplot(data=penguins, mapping=aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(mapping=aes(color="species", shape="species"))
    + geom_smooth(method="lm")
)
```
This one allows us to put different shapes and colors to species which allows us to visiually see them a lot faster. The pink line that goes through is a linear regression smoothing line. 
Conclusion: The penguins with bigger flippers do have bigger mass.